# Generated by Django 3.2.8 on 2022-02-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0002_auto_20220215_0154'),
        ('authentication', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
