# Generated by Django 3.2.8 on 2022-03-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsApp', '0003_auto_20220225_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='upload',
            new_name='post',
        ),
    ]
